services:
  postgres:
    image: postgres:15-alpine
    container_name: sassntial_admin_fresh_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sassntial_admin_fresh_db
      POSTGRES_USER: sassntial_admin_fresh
      POSTGRES_PASSWORD: sassntial@admin
    ports:
      - "5441:5432"
    volumes:
      - sassntial_admin_fresh_postgres_data:/var/lib/postgresql/data
    networks:
      - sassntial_admin_fresh_network

  redis:
    image: redis:7-alpine
    container_name: sassntial_admin_fresh_redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - sassntial_admin_fresh_redis_data:/data
    networks:
      - sassntial_admin_fresh_network

volumes:
  sassntial_admin_fresh_postgres_data:
  sassntial_admin_fresh_redis_data:

networks:
  sassntial_admin_fresh_network:
    driver: bridge
